# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 679)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 670))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 750))
        MainWindow.setBaseSize(QtCore.QSize(1200, 0))
        MainWindow.setStyleSheet("QStatusBar\n"
"{\n"
"    color: white;\n"
"    background-color: rgb(53, 53, 53);\n"
"    font: 9pt \"Montserrat\";\n"
"}\n"
"QStatusBar::item\n"
"{\n"
"    border: 0px transparent dark;\n"
"}\n"
"#centralwidget{\n"
"    \n"
"    background-color: rgb(46, 52, 54);\n"
"    border-image: url(./src/UI/images/TgFZH.jpg);\n"
"}\n"
"QProgressBar {\n"
"background-color: rgb(255, 255, 255);\n"
"  color: black;\n"
"border: 0.2ex solid black;\n"
"  border-top-right-radius: 5px;\n"
"  border-bottom-right-radius: 5px;\n"
"  text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"background-color: rgb(148, 148, 148);\n"
"color: white;\n"
"border-top-right-radius: 5px;\n"
"border-bottom-right-radius: 5px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_header = QtWidgets.QFrame(self.centralwidget)
        self.frame_header.setMinimumSize(QtCore.QSize(0, 78))
        self.frame_header.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_header.setStyleSheet("#frame_header{\n"
"background-color: white;\n"
"}")
        self.frame_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_header.setObjectName("frame_header")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_header)
        self.gridLayout_12.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_12.setContentsMargins(0, 9, 0, 9)
        self.gridLayout_12.setVerticalSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.pushButton_sound = QtWidgets.QPushButton(self.frame_header)
        self.pushButton_sound.setMaximumSize(QtCore.QSize(50, 40))
        self.pushButton_sound.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./src/UI/images/fkzfaalief3i.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_sound.setIcon(icon)
        self.pushButton_sound.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_sound.setObjectName("pushButton_sound")
        self.gridLayout_12.addWidget(self.pushButton_sound, 0, 1, 1, 1)
        self.label_logo = QtWidgets.QLabel(self.frame_header)
        self.label_logo.setMinimumSize(QtCore.QSize(0, 60))
        self.label_logo.setMaximumSize(QtCore.QSize(350, 60))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("./src/UI/images/YfZiodQJx.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setObjectName("label_logo")
        self.gridLayout_12.addWidget(self.label_logo, 0, 3, 1, 1)
        self.pushButton_quit = QtWidgets.QPushButton(self.frame_header)
        self.pushButton_quit.setMaximumSize(QtCore.QSize(50, 40))
        self.pushButton_quit.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./src/UI/images/gkhutxr3cyyn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_quit.setIcon(icon1)
        self.pushButton_quit.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.gridLayout_12.addWidget(self.pushButton_quit, 0, 5, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem2, 0, 6, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_header, 0, 0, 1, 3)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(800, 506))
        self.frame.setStyleSheet("#frame{\n"
"    border: none;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_17 = QtWidgets.QFrame(self.frame)
        self.frame_17.setGeometry(QtCore.QRect(150, 345, 106, 23))
        self.frame_17.setMinimumSize(QtCore.QSize(100, 23))
        self.frame_17.setMaximumSize(QtCore.QSize(110, 30))
        self.frame_17.setStyleSheet("#frame_17{\n"
"    border: none;\n"
"}")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_pl_5_dealer = QtWidgets.QLabel(self.frame_17)
        self.label_pl_5_dealer.setMinimumSize(QtCore.QSize(21, 21))
        self.label_pl_5_dealer.setMaximumSize(QtCore.QSize(21, 21))
        self.label_pl_5_dealer.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(0, 30, 13, 255), stop:0.272727 rgba(0, 64, 28, 255), stop:0.6875 rgba(0, 54, 23, 255), stop:1 rgba(0, 16, 7, 255));\n"
"color: white;\n"
"font: 10pt \"Montserrat\";\n"
"border: 2px solid black;\n"
"border-style: inset;\n"
"border-color: rgb(0, 34, 14);\n"
"padding-left: 2px;\n"
"border-radius: 5px;")
        self.label_pl_5_dealer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pl_5_dealer.setObjectName("label_pl_5_dealer")
        self.horizontalLayout_6.addWidget(self.label_pl_5_dealer)
        self.label_pl_5_bet = QtWidgets.QLabel(self.frame_17)
        self.label_pl_5_bet.setMinimumSize(QtCore.QSize(21, 21))
        self.label_pl_5_bet.setMaximumSize(QtCore.QSize(21, 21))
        self.label_pl_5_bet.setText("")
        self.label_pl_5_bet.setPixmap(QtGui.QPixmap("./src/UI/images/jLyAbQqTfW.png"))
        self.label_pl_5_bet.setScaledContents(True)
        self.label_pl_5_bet.setObjectName("label_pl_5_bet")
        self.horizontalLayout_6.addWidget(self.label_pl_5_bet)
        self.label_pl_5_bet_amt = QtWidgets.QLabel(self.frame_17)
        self.label_pl_5_bet_amt.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_pl_5_bet_amt.setStyleSheet("color: white;\n"
"font: 11pt \"Montserrat\";\n"
"border-radius: 5px;\n"
"background-color: transparent;")
        self.label_pl_5_bet_amt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_pl_5_bet_amt.setWordWrap(True)
        self.label_pl_5_bet_amt.setObjectName("label_pl_5_bet_amt")
        self.horizontalLayout_6.addWidget(self.label_pl_5_bet_amt)
        self.frame_pl_6 = QtWidgets.QFrame(self.frame)
        self.frame_pl_6.setGeometry(QtCore.QRect(0, 50, 150, 130))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_pl_6.sizePolicy().hasHeightForWidth())
        self.frame_pl_6.setSizePolicy(sizePolicy)
        self.frame_pl_6.setMinimumSize(QtCore.QSize(150, 130))
        self.frame_pl_6.setMaximumSize(QtCore.QSize(108, 136))
        self.frame_pl_6.setStyleSheet("#frame_pl_6{\n"
"    border: none;\n"
"}")
        self.frame_pl_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pl_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pl_6.setObjectName("frame_pl_6")
        self.frame_3 = QtWidgets.QFrame(self.frame_pl_6)
        self.frame_3.setGeometry(QtCore.QRect(0, 70, 150, 52))
        self.frame_3.setMaximumSize(QtCore.QSize(150, 60))
        self.frame_3.setStyleSheet("#frame_3{\n"
"    border: none;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_pl_6_name = QtWidgets.QLabel(self.frame_3)
        self.label_pl_6_name.setMinimumSize(QtCore.QSize(110, 26))
        self.label_pl_6_name.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_pl_6_name.setStyleSheet("color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(70, 70, 70, 255), stop:0.142045 rgba(70, 70, 70, 255), stop:0.494318 rgba(12, 12, 12, 255), stop:1 rgba(12, 12, 12, 255));\n"
"border: 1px solid white;\n"
"border-radius: 5px;")
        self.label_pl_6_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pl_6_name.setObjectName("label_pl_6_name")
        self.verticalLayout_5.addWidget(self.label_pl_6_name)
        self.label_pl_6_btc = QtWidgets.QLabel(self.frame_3)
        self.label_pl_6_btc.setMinimumSize(QtCore.QSize(110, 26))
        self.label_pl_6_btc.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_pl_6_btc.setStyleSheet("color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(70, 70, 70, 255), stop:0.142045 rgba(70, 70, 70, 255), stop:0.494318 rgba(12, 12, 12, 255), stop:1 rgba(12, 12, 12, 255));\n"
"border: 1px solid white;\n"
"border-radius: 5px;")
        self.label_pl_6_btc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pl_6_btc.setObjectName("label_pl_6_btc")
        self.verticalLayout_5.addWidget(self.label_pl_6_btc)
        self.label_p6c2 = QtWidgets.QLabel(self.frame_pl_6)
        self.label_p6c2.setGeometry(QtCore.QRect(35, 21, 35, 50))
        self.label_p6c2.setMinimumSize(QtCore.QSize(0, 50))
        self.label_p6c2.setMaximumSize(QtCore.QSize(35, 50))
        self.label_p6c2.setStyleSheet("")
        self.label_p6c2.setText("")
        self.label_p6c2.setPixmap(QtGui.QPixmap("./src/UI/images/41x60/back.png"))
        self.label_p6c2.setScaledContents(True)
        self.label_p6c2.setObjectName("label_p6c2")
        self.label_p6c1 = QtWidgets.QLabel(self.frame_pl_6)
        self.label_p6c1.setGeometry(QtCore.QRect(80, 21, 35, 50))
        self.label_p6c1.setMinimumSize(QtCore.QSize(0, 50))
        self.label_p6c1.setMaximumSize(QtCore.QSize(35, 50))
        self.label_p6c1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_p6c1.setStyleSheet("")
        self.label_p6c1.setText("")
        self.label_p6c1.setPixmap(QtGui.QPixmap("./src/UI/images/41x60/back.png"))
        self.label_p6c1.setScaledContents(True)
        self.label_p6c1.setObjectName("label_p6c1")
        self.pl_6_avatar = QtWidgets.QLabel(self.frame_pl_6)
        self.pl_6_avatar.setGeometry(QtCore.QRect(50, 21, 50, 50))
        self.pl_6_avatar.setMinimumSize(QtCore.QSize(50, 50))
        self.pl_6_avatar.setText("")
        self.pl_6_avatar.setPixmap(QtGui.QPixmap("./src/UI/images/ksdfvQWC.png"))
        self.pl_6_avatar.setScaledContents(True)
        self.pl_6_avatar.setObjectName("pl_6_avatar")
        self.layoutWidget = QtWidgets.QWidget(self.frame_pl_6)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 130, 23))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setContentsMargins(9, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clock_label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.clock_label_6.setMinimumSize(QtCore.QSize(20, 21))
        self.clock_label_6.setMaximumSize(QtCore.QSize(20, 21))
        self.clock_label_6.setText("")
        self.clock_label_6.setPixmap(QtGui.QPixmap("./src/UI/images/fo2woqfz1mxw.png"))
        self.clock_label_6.setScaledContents(True)
        self.clock_label_6.setObjectName("clock_label_6")
        self.horizontalLayout.addWidget(self.clock_label_6)
        self.progressBar_pl_6 = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar_pl_6.setMinimumSize(QtCore.QSize(100, 15))
        self.progressBar_pl_6.setMaximumSize(QtCore.QSize(100, 15))
        self.progressBar_pl_6.setStyleSheet("border-left: none;\n"
"margin-left: -2px;")
        self.progressBar_pl_6.setProperty("value", 25)
        self.progressBar_pl_6.setTextVisible(False)
        self.progressBar_pl_6.setObjectName("progressBar_pl_6")
        self.horizontalLayout.addWidget(self.progressBar_pl_6)
        self.frame_pl_3 = QtWidgets.QFrame(self.frame)
        self.frame_pl_3.setGeometry(QtCore.QRect(650, 320, 150, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_pl_3.sizePolicy().hasHeightForWidth())
        self.frame_pl_3.setSizePolicy(sizePolicy)
        self.frame_pl_3.setMinimumSize(QtCore.QSize(150, 130))
        self.frame_pl_3.setMaximumSize(QtCore.QSize(108, 150))
        self.frame_pl_3.setStyleSheet("#frame_pl_3{\n"
"    border: none;\n"
"}")
        self.frame_pl_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pl_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pl_3.setObjectName("frame_pl_3")
        self.frame_9 = QtWidgets.QFrame(self.frame_pl_3)
        self.frame_9.setGeometry(QtCore.QRect(2, 78, 150, 60))
        self.frame_9.setMaximumSize(QtCore.QSize(150, 60))
        self.frame_9.setStyleSheet("#frame_9{\n"
"    border: none;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_pl_3_name = QtWidgets.QLabel(self.frame_9)
        self.label_pl_3_name.setMinimumSize(QtCore.QSize(110, 26))
        self.label_pl_3_name.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_pl_3_name.setStyleSheet("color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(70, 70, 70, 255), stop:0.142045 rgba(70, 70, 70, 255), stop:0.494318 rgba(12, 12, 12, 255), stop:1 rgba(12, 12, 12, 255));\n"
"border: 1px solid white;\n"
"border-radius: 5px;")
        self.label_pl_3_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pl_3_name.setObjectName("label_pl_3_name")
        self.verticalLayout_3.addWidget(self.label_pl_3_name)
        self.label_pl_3_btc = QtWidgets.QLabel(self.frame_9)
        self.label_pl_3_btc.setMinimumSize(QtCore.QSize(110, 26))
        self.label_pl_3_btc.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_pl_3_btc.setStyleSheet("color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(70, 70, 70, 255), stop:0.142045 rgba(70, 70, 70, 255), stop:0.494318 rgba(12, 12, 12, 255), stop:1 rgba(12, 12, 12, 255));\n"
"border: 1px solid white;\n"
"border-radius: 5px;")
        self.label_pl_3_btc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pl_3_btc.setObjectName("label_pl_3_btc")
        self.verticalLayout_3.addWidget(self.label_pl_3_btc)
        self.label_p3c2 = QtWidgets.QLabel(self.frame_pl_3)
        self.label_p3c2.setGeometry(QtCore.QRect(85, 29, 35, 50))
        self.label_p3c2.setMinimumSize(QtCore.QSize(0, 50))
        self.label_p3c2.setMaximumSize(QtCore.QSize(35, 50))
        self.label_p3c2.setStyleSheet("")
        self.label_p3c2.setText("")
        self.label_p3c2.setPixmap(QtGui.QPixmap("./src/UI/images/41x60/back.png"))
        self.label_p3c2.setScaledContents(True)
        self.label_p3c2.setObjectName("label_p3c2")
        self.label_p3c1 = QtWidgets.QLabel(self.frame_pl_3)
        self.label_p3c1.setGeometry(QtCore.QRect(40, 29, 35, 50))
        self.label_p3c1.setMinimumSize(QtCore.QSize(0, 50))
        self.label_p3c1.setMaximumSize(QtCore.QSize(35, 50))
        self.label_p3c1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_p3c1.setStyleSheet("")
        self.label_p3c1.setText("")
        self.label_p3c1.setPixmap(QtGui.QPixmap("./src/UI/images/41x60/back.png"))
        self.label_p3c1.setScaledContents(True)
        self.label_p3c1.setObjectName("label_p3c1")
        self.pl_3_avatar = QtWidgets.QLabel(self.frame_pl_3)
        self.pl_3_avatar.setGeometry(QtCore.QRect(50, 29, 50, 50))
        self.pl_3_avatar.setMinimumSize(QtCore.QSize(50, 50))
        self.pl_3_avatar.setText("")
        self.pl_3_avatar.setPixmap(QtGui.QPixmap("./src/UI/images/ksdfvQWC.png"))
        self.pl_3_avatar.setScaledContents(True)
        self.pl_3_avatar.setObjectName("pl_3_avatar")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_pl_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 0, 130, 23))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_12.setContentsMargins(9, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.clock_label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.clock_label_3.setMinimumSize(QtCore.QSize(20, 21))
        self.clock_label_3.setMaximumSize(QtCore.QSize(20, 21))
        self.clock_label_3.setText("")
        self.clock_label_3.setPixmap(QtGui.QPixmap("./src/UI/images/fo2woqfz1mxw.png"))
        self.clock_label_3.setScaledContents(True)
        self.clock_label_3.setObjectName("clock_label_3")
        self.horizontalLayout_12.addWidget(self.clock_label_3)
        self.progressBar_pl_3 = QtWidgets.QProgressBar(self.layoutWidget1)
        self.progressBar_pl_3.setMinimumSize(QtCore.QSize(100, 15))
        self.progressBar_pl_3.setMaximumSize(QtCore.QSize(100, 15))
        self.progressBar_pl_3.setStyleSheet("border-left: none;\n"
"margin-left: -2px;")
        self.progressBar_pl_3.setProperty("value", 25)
        self.progressBar_pl_3.setTextVisible(False)
        self.progressBar_pl_3.setObjectName("progressBar_pl_3")
        self.horizontalLayout_12.addWidget(self.progressBar_pl_3)
        self.frame_pl_4 = QtWidgets.QFrame(self.frame)
        self.frame_pl_4.setGeometry(QtCore.QRect(329, 360, 151, 145))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_pl_4.sizePolicy().hasHeightForWidth())
        self.frame_pl_4.setSizePolicy(sizePolicy)
        self.frame_pl_4.setMinimumSize(QtCore.QSize(116, 145))
        self.frame_pl_4.setMaximumSize(QtCore.QSize(160, 155))
        self.frame_pl_4.setStyleSheet("#frame_pl_4{\n"
"    border: none;\n"
"}")
        self.frame_pl_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pl_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pl_4.setObjectName("frame_pl_4")
        self.label_p4c2 = QtWidgets.QLabel(self.frame_pl_4)
        self.label_p4c2.setGeometry(QtCore.QRect(40, 33, 35, 50))
        self.label_p4c2.setMinimumSize(QtCore.QSize(0, 50))
        self.label_p4c2.setMaximumSize(QtCore.QSize(35, 50))
        self.label_p4c2.setStyleSheet("border: 0px solid transparent;")
        self.label_p4c2.setText("")
        self.label_p4c2.setPixmap(QtGui.QPixmap("./src/UI/images/41x60/back.png"))
        self.label_p4c2.setScaledContents(True)
        self.label_p4c2.setObjectName("label_p4c2")
        self.frame_11 = QtWidgets.QFrame(self.frame_pl_4)
        self.frame_11.setGeometry(QtCore.QRect(1, 82, 150, 60))
        self.frame_11.setMaximumSize(QtCore.QSize(150, 60))
        self.frame_11.setStyleSheet("#frame_11{\n"
"    border: none;\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 1)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_pl_4_name = QtWidgets.QLabel(self.frame_11)
        self.label_pl_4_name.setMinimumSize(QtCore.QSize(110, 26))
        self.label_pl_4_name.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_pl_4_name.setStyleSheet("color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(70, 70, 70, 255), stop:0.142045 rgba(70, 70, 70, 255), stop:0.494318 rgba(12, 12, 12, 255), stop:1 rgba(12, 12, 12, 255));\n"
"border: 1px solid white;\n"
"border-radius: 5px;")
        self.label_pl_4_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pl_4_name.setObjectName("label_pl_4_name")
        self.verticalLayout_6.addWidget(self.label_pl_4_name)
        self.label_pl_4_btc = QtWidgets.QLabel(self.frame_11)
        self.label_pl_4_btc.setMinimumSize(QtCore.QSize(110, 26))
        self.label_pl_4_btc.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_pl_4_btc.setStyleSheet("color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(70, 70, 70, 255), stop:0.142045 rgba(70, 70, 70, 255), stop:0.494318 rgba(12, 12, 12, 255), stop:1 rgba(12, 12, 12, 255));\n"
"border: 1px solid white;\n"
"border-radius: 5px;")
        self.label_pl_4_btc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pl_4_btc.setObjectName("label_pl_4_btc")
        self.verticalLayout_6.addWidget(self.label_pl_4_btc)
        self.label_p4c1 = QtWidgets.QLabel(self.frame_pl_4)
        self.label_p4c1.setGeometry(QtCore.QRect(85, 33, 35, 50))
        self.label_p4c1.setMinimumSize(QtCore.QSize(0, 50))
        self.label_p4c1.setMaximumSize(QtCore.QSize(35, 50))
        self.label_p4c1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_p4c1.setStyleSheet("border: 0px solid transparent;")
        self.label_p4c1.setText("")
        self.label_p4c1.setPixmap(QtGui.QPixmap("./src/UI/images/41x60/back.png"))
        self.label_p4c1.setScaledContents(True)
        self.label_p4c1.setObjectName("label_p4c1")
        self.pl_4_avatar = QtWidgets.QLabel(self.frame_pl_4)
        self.pl_4_avatar.setGeometry(QtCore.QRect(50, 33, 50, 50))
        self.pl_4_avatar.setMinimumSize(QtCore.QSize(50, 50))
        self.pl_4_avatar.setText("")
        self.pl_4_avatar.setPixmap(QtGui.QPixmap("./src/UI/images/ksdfvQWC.png"))
        self.pl_4_avatar.setScaledContents(True)
        self.pl_4_avatar.setObjectName("pl_4_avatar")
        self.frame_18 = QtWidgets.QFrame(self.frame_pl_4)
        self.frame_18.setGeometry(QtCore.QRect(30, 0, 110, 33))
        self.frame_18.setMinimumSize(QtCore.QSize(100, 33))
        self.frame_18.setMaximumSize(QtCore.QSize(115, 30))
        self.frame_18.setStyleSheet("#frame_18{\n"
"    border: none;\n"
"}")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_pl_4_dealer = QtWidgets.QLabel(self.frame_18)
        self.label_pl_4_dealer.setMinimumSize(QtCore.QSize(21, 21))
        self.label_pl_4_dealer.setMaximumSize(QtCore.QSize(21, 21))
        self.label_pl_4_dealer.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(0, 30, 13, 255), stop:0.272727 rgba(0, 64, 28, 255), stop:0.6875 rgba(0, 54, 23, 255), stop:1 rgba(0, 16, 7, 255));\n"
"color: white;\n"
"font: 10pt \"Montserrat\";\n"
"border: 2px solid black;\n"
"border-style: inset;\n"
"border-color: rgb(0, 34, 14);\n"
"padding-left: 2px;\n"
"border-radius: 5px;")
        self.label_pl_4_dealer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pl_4_dealer.setObjectName("label_pl_4_dealer")
        self.horizontalLayout_8.addWidget(self.label_pl_4_dealer)
        self.label_pl_4_bet = QtWidgets.QLabel(self.frame_18)
        self.label_pl_4_bet.setMinimumSize(QtCore.QSize(21, 21))
        self.label_pl_4_bet.setMaximumSize(QtCore.QSize(21, 21))
        self.label_pl_4_bet.setText("")
        self.label_pl_4_bet.setPixmap(QtGui.QPixmap("./src/UI/images/jLyAbQqTfW.png"))
        self.label_pl_4_bet.setScaledContents(True)
        self.label_pl_4_bet.setObjectName("label_pl_4_bet")
        self.horizontalLayout_8.addWidget(self.label_pl_4_bet)
        self.label_pl_4_bet_amt = QtWidgets.QLabel(self.frame_18)
        self.label_pl_4_bet_amt.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_pl_4_bet_amt.setStyleSheet("color: white;\n"
"font: 11pt \"Montserrat\";\n"
"border-radius: 5px;\n"
"background-color: transparent;")
        self.label_pl_4_bet_amt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_pl_4_bet_amt.setWordWrap(True)
        self.label_pl_4_bet_amt.setObjectName("label_pl_4_bet_amt")
        self.horizontalLayout_8.addWidget(self.label_pl_4_bet_amt)
        self.frame_pl_5 = QtWidgets.QFrame(self.frame)
        self.frame_pl_5.setGeometry(QtCore.QRect(0, 330, 150, 130))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_pl_5.sizePolicy().hasHeightForWidth())
        self.frame_pl_5.setSizePolicy(sizePolicy)
        self.frame_pl_5.setMinimumSize(QtCore.QSize(150, 130))
        self.frame_pl_5.setMaximumSize(QtCore.QSize(150, 136))
        self.frame_pl_5.setStyleSheet("#frame_pl_5{\n"
"    border: none;\n"
"}")
        self.frame_pl_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pl_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pl_5.setObjectName("frame_pl_5")
        self.label_p5c1 = QtWidgets.QLabel(self.frame_pl_5)
        self.label_p5c1.setGeometry(QtCore.QRect(36, 21, 35, 50))
        self.label_p5c1.setMinimumSize(QtCore.QSize(0, 50))
        self.label_p5c1.setMaximumSize(QtCore.QSize(35, 50))
        self.label_p5c1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_p5c1.setStyleSheet("")
        self.label_p5c1.setText("")
        self.label_p5c1.setPixmap(QtGui.QPixmap("./src/UI/images/41x60/back.png"))
        self.label_p5c1.setScaledContents(True)
        self.label_p5c1.setObjectName("label_p5c1")
        self.label_p5c2 = QtWidgets.QLabel(self.frame_pl_5)
        self.label_p5c2.setGeometry(QtCore.QRect(80, 21, 35, 50))
        self.label_p5c2.setMinimumSize(QtCore.QSize(0, 50))
        self.label_p5c2.setMaximumSize(QtCore.QSize(35, 50))
        self.label_p5c2.setStyleSheet("")
        self.label_p5c2.setText("")
        self.label_p5c2.setPixmap(QtGui.QPixmap("./src/UI/images/41x60/back.png"))
        self.label_p5c2.setScaledContents(True)
        self.label_p5c2.setObjectName("label_p5c2")
        self.frame_5 = QtWidgets.QFrame(self.frame_pl_5)
        self.frame_5.setGeometry(QtCore.QRect(0, 70, 150, 53))
        self.frame_5.setMaximumSize(QtCore.QSize(150, 60))
        self.frame_5.setStyleSheet("#frame_5{\n"
"    border: none;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_pl_5_name = QtWidgets.QLabel(self.frame_5)
        self.label_pl_5_name.setMinimumSize(QtCore.QSize(110, 26))
        self.label_pl_5_name.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_pl_5_name.setStyleSheet("color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(70, 70, 70, 255), stop:0.142045 rgba(70, 70, 70, 255), stop:0.494318 rgba(12, 12, 12, 255), stop:1 rgba(12, 12, 12, 255));\n"
"border: 1px solid white;\n"
"border-radius: 5px;")
        self.label_pl_5_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pl_5_name.setObjectName("label_pl_5_name")
        self.verticalLayout_4.addWidget(self.label_pl_5_name)
        self.label_pl_5_btc = QtWidgets.QLabel(self.frame_5)
        self.label_pl_5_btc.setMinimumSize(QtCore.QSize(110, 26))
        self.label_pl_5_btc.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_pl_5_btc.setStyleSheet("color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(70, 70, 70, 255), stop:0.142045 rgba(70, 70, 70, 255), stop:0.494318 rgba(12, 12, 12, 255), stop:1 rgba(12, 12, 12, 255));\n"
"border: 1px solid white;\n"
"border-radius: 5px;")
        self.label_pl_5_btc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pl_5_btc.setObjectName("label_pl_5_btc")
        self.verticalLayout_4.addWidget(self.label_pl_5_btc)
        self.pl_5_avatar = QtWidgets.QLabel(self.frame_pl_5)
        self.pl_5_avatar.setGeometry(QtCore.QRect(50, 21, 50, 50))
        self.pl_5_avatar.setMinimumSize(QtCore.QSize(50, 50))
        self.pl_5_avatar.setText("")
        self.pl_5_avatar.setPixmap(QtGui.QPixmap("./src/UI/images/ksdfvQWC.png"))
        self.pl_5_avatar.setScaledContents(True)
        self.pl_5_avatar.setObjectName("pl_5_avatar")
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_pl_5)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 0, 130, 23))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_10.setContentsMargins(9, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.clock_label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.clock_label_5.setMinimumSize(QtCore.QSize(20, 21))
        self.clock_label_5.setMaximumSize(QtCore.QSize(20, 21))
        self.clock_label_5.setText("")
        self.clock_label_5.setPixmap(QtGui.QPixmap("./src/UI/images/fo2woqfz1mxw.png"))
        self.clock_label_5.setScaledContents(True)
        self.clock_label_5.setObjectName("clock_label_5")
        self.horizontalLayout_10.addWidget(self.clock_label_5)
        self.progressBar_pl_5 = QtWidgets.QProgressBar(self.layoutWidget2)
        self.progressBar_pl_5.setMinimumSize(QtCore.QSize(100, 15))
        self.progressBar_pl_5.setMaximumSize(QtCore.QSize(100, 15))
        self.progressBar_pl_5.setStyleSheet("border-left: none;\n"
"margin-left: -2px;")
        self.progressBar_pl_5.setProperty("value", 25)
        self.progressBar_pl_5.setTextVisible(False)
        self.progressBar_pl_5.setObjectName("progressBar_pl_5")
        self.horizontalLayout_10.addWidget(self.progressBar_pl_5)
        self.frame_19 = QtWidgets.QFrame(self.frame)
        self.frame_19.setGeometry(QtCore.QRect(550, 350, 101, 23))
        self.frame_19.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_19.setMaximumSize(QtCore.QSize(110, 30))
        self.frame_19.setStyleSheet("#frame_19{\n"
"    border: none;\n"
"}")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(8)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_pl_3_bet = QtWidgets.QLabel(self.frame_19)
        self.label_pl_3_bet.setMinimumSize(QtCore.QSize(21, 21))
        self.label_pl_3_bet.setMaximumSize(QtCore.QSize(21, 21))
        self.label_pl_3_bet.setText("")
        self.label_pl_3_bet.setPixmap(QtGui.QPixmap("./src/UI/images/jLyAbQqTfW.png"))
        self.label_pl_3_bet.setScaledContents(True)
        self.label_pl_3_bet.setObjectName("label_pl_3_bet")
        self.horizontalLayout_9.addWidget(self.label_pl_3_bet)
        self.label_pl_3_bet_amt = QtWidgets.QLabel(self.frame_19)
        self.label_pl_3_bet_amt.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_pl_3_bet_amt.setStyleSheet("color: white;\n"
"font: 11pt \"Montserrat\";\n"
"border-radius: 5px;\n"
"background-color: transparent;")
        self.label_pl_3_bet_amt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_pl_3_bet_amt.setWordWrap(True)
        self.label_pl_3_bet_amt.setObjectName("label_pl_3_bet_amt")
        self.horizontalLayout_9.addWidget(self.label_pl_3_bet_amt)
        self.label_pl_3_dealer = QtWidgets.QLabel(self.frame_19)
        self.label_pl_3_dealer.setMinimumSize(QtCore.QSize(21, 21))
        self.label_pl_3_dealer.setMaximumSize(QtCore.QSize(21, 21))
        self.label_pl_3_dealer.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(0, 30, 13, 255), stop:0.272727 rgba(0, 64, 28, 255), stop:0.6875 rgba(0, 54, 23, 255), stop:1 rgba(0, 16, 7, 255));\n"
"color: white;\n"
"font: 10pt \"Montserrat\";\n"
"border: 2px solid black;\n"
"border-style: inset;\n"
"border-color: rgb(0, 34, 14);\n"
"padding-left: 2px;\n"
"border-radius: 5px;")
        self.label_pl_3_dealer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pl_3_dealer.setObjectName("label_pl_3_dealer")
        self.horizontalLayout_9.addWidget(self.label_pl_3_dealer)
        self.frame_15 = QtWidgets.QFrame(self.frame)
        self.frame_15.setGeometry(QtCore.QRect(150, 150, 106, 23))
        self.frame_15.setMinimumSize(QtCore.QSize(100, 23))
        self.frame_15.setMaximumSize(QtCore.QSize(110, 30))
        self.frame_15.setStyleSheet("#frame_15{\n"
"    border: none;\n"
"}")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_pl_6_dealer = QtWidgets.QLabel(self.frame_15)
        self.label_pl_6_dealer.setMinimumSize(QtCore.QSize(21, 21))
        self.label_pl_6_dealer.setMaximumSize(QtCore.QSize(21, 21))
        self.label_pl_6_dealer.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(0, 30, 13, 255), stop:0.272727 rgba(0, 64, 28, 255), stop:0.6875 rgba(0, 54, 23, 255), stop:1 rgba(0, 16, 7, 255));\n"
"color: white;\n"
"font: 10pt \"Montserrat\";\n"
"border: 2px solid black;\n"
"border-style: inset;\n"
"border-color: rgb(0, 34, 14);\n"
"padding-left: 2px;\n"
"border-radius: 5px;")
        self.label_pl_6_dealer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pl_6_dealer.setObjectName("label_pl_6_dealer")
        self.horizontalLayout_4.addWidget(self.label_pl_6_dealer)
        self.label_pl_6_bet = QtWidgets.QLabel(self.frame_15)
        self.label_pl_6_bet.setMinimumSize(QtCore.QSize(21, 21))
        self.label_pl_6_bet.setMaximumSize(QtCore.QSize(21, 21))
        self.label_pl_6_bet.setText("")
        self.label_pl_6_bet.setPixmap(QtGui.QPixmap("./src/UI/images/jLyAbQqTfW.png"))
        self.label_pl_6_bet.setScaledContents(True)
        self.label_pl_6_bet.setObjectName("label_pl_6_bet")
        self.horizontalLayout_4.addWidget(self.label_pl_6_bet)
        self.label_pl_6_bet_amt = QtWidgets.QLabel(self.frame_15)
        self.label_pl_6_bet_amt.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_pl_6_bet_amt.setStyleSheet("color: white;\n"
"font: 11pt \"Montserrat\";\n"
"border-radius: 5px;\n"
"background-color: transparent;")
        self.label_pl_6_bet_amt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_pl_6_bet_amt.setWordWrap(True)
        self.label_pl_6_bet_amt.setObjectName("label_pl_6_bet_amt")
        self.horizontalLayout_4.addWidget(self.label_pl_6_bet_amt)
        self.frame_table_top = QtWidgets.QFrame(self.frame)
        self.frame_table_top.setGeometry(QtCore.QRect(260, 190, 261, 149))
        self.frame_table_top.setMinimumSize(QtCore.QSize(245, 143))
        self.frame_table_top.setMaximumSize(QtCore.QSize(720, 152))
        self.frame_table_top.setStyleSheet("#frame_table_top{\n"
"    border: none;\n"
"}")
        self.frame_table_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_table_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_table_top.setMidLineWidth(1)
        self.frame_table_top.setObjectName("frame_table_top")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_table_top)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setHorizontalSpacing(8)
        self.gridLayout_6.setVerticalSpacing(5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_c3 = QtWidgets.QLabel(self.frame_table_top)
        self.label_c3.setText("")
        self.label_c3.setPixmap(QtGui.QPixmap("./src/UI/images/41x60/back.png"))
        self.label_c3.setObjectName("label_c3")
        self.gridLayout_6.addWidget(self.label_c3, 1, 2, 1, 1)
        self.label_c1 = QtWidgets.QLabel(self.frame_table_top)
        self.label_c1.setText("")
        self.label_c1.setPixmap(QtGui.QPixmap("./src/UI/images/41x60/back.png"))
        self.label_c1.setObjectName("label_c1")
        self.gridLayout_6.addWidget(self.label_c1, 1, 0, 1, 1)
        self.label_c2 = QtWidgets.QLabel(self.frame_table_top)
        self.label_c2.setText("")
        self.label_c2.setPixmap(QtGui.QPixmap("./src/UI/images/41x60/back.png"))
        self.label_c2.setObjectName("label_c2")
        self.gridLayout_6.addWidget(self.label_c2, 1, 1, 1, 1)
        self.label_c5 = QtWidgets.QLabel(self.frame_table_top)
        self.label_c5.setText("")
        self.label_c5.setPixmap(QtGui.QPixmap("./src/UI/images/41x60/back.png"))
        self.label_c5.setObjectName("label_c5")
        self.gridLayout_6.addWidget(self.label_c5, 1, 4, 1, 1)
        self.label_c4 = QtWidgets.QLabel(self.frame_table_top)
        self.label_c4.setText("")
        self.label_c4.setPixmap(QtGui.QPixmap("./src/UI/images/41x60/back.png"))
        self.label_c4.setObjectName("label_c4")
        self.gridLayout_6.addWidget(self.label_c4, 1, 3, 1, 1)
        self.label_result = QtWidgets.QLabel(self.frame_table_top)
        self.label_result.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_result.setStyleSheet("font: 11pt \"Montserrat\";\n"
"color: white;\n"
"background-color: rgb(118, 0, 0);\n"
"border: 1px inset transparent;\n"
"border-radius: 19;\n"
"padding: 4;\n"
"border-bottom: 3px groove rgb(158, 26, 26);\n"
"border-right: 2px groove rgb(158, 26, 26);\n"
"border-left: 2px groove rgb(158, 26, 26);")
        self.label_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_result.setObjectName("label_result")
        self.gridLayout_6.addWidget(self.label_result, 0, 0, 1, 5)
        self.label_pot = QtWidgets.QLabel(self.frame_table_top)
        self.label_pot.setMaximumSize(QtCore.QSize(275, 40))
        self.label_pot.setStyleSheet("/*font: 11pt \"Montserrat\";\n"
"color: white;\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(1, 21, 10, 255), stop:0.0852273 rgba(4, 46, 22, 255), stop:0.204545 rgba(3, 36, 17, 255), stop:0.818182 rgba(5, 59, 28, 255), stop:0.909091 rgba(5, 63, 30, 255), stop:1 rgba(3, 36, 17, 255));\n"
"border-style: inset;\n"
"border-color: rgb(0, 49, 21);\n"
"border-radius: 10px;*/\n"
"padding: 10px;\n"
"background: #0d572b;\n"
"border: 1px solid transparent;\n"
"border-left: 1px solid #157c3d;\n"
"border-right: 1px solid #157c3d;\n"
"border-bottom: 2px solid #157c3d;\n"
"border-radius: 20px;\n"
"text-align: center;\n"
"font-size: 18px;\n"
"color: #fff;")
        self.label_pot.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pot.setObjectName("label_pot")
        self.gridLayout_6.addWidget(self.label_pot, 2, 0, 1, 5)
        self.frame_pl_1 = QtWidgets.QFrame(self.frame)
        self.frame_pl_1.setGeometry(QtCore.QRect(320, 10, 151, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_pl_1.sizePolicy().hasHeightForWidth())
        self.frame_pl_1.setSizePolicy(sizePolicy)
        self.frame_pl_1.setMinimumSize(QtCore.QSize(150, 140))
        self.frame_pl_1.setMaximumSize(QtCore.QSize(160, 200))
        self.frame_pl_1.setStyleSheet("#frame_pl_1{\n"
"    border: none;\n"
"}")
        self.frame_pl_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pl_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pl_1.setObjectName("frame_pl_1")
        self.frame_pl_1_det = QtWidgets.QFrame(self.frame_pl_1)
        self.frame_pl_1_det.setGeometry(QtCore.QRect(1, 61, 150, 54))
        self.frame_pl_1_det.setMaximumSize(QtCore.QSize(150, 60))
        self.frame_pl_1_det.setStyleSheet("#frame_pl_1_det{\n"
"    border: none;\n"
"}")
        self.frame_pl_1_det.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pl_1_det.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pl_1_det.setObjectName("frame_pl_1_det")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_pl_1_det)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_pl_1_name = QtWidgets.QLabel(self.frame_pl_1_det)
        self.label_pl_1_name.setMinimumSize(QtCore.QSize(110, 26))
        self.label_pl_1_name.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_pl_1_name.setStyleSheet("color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(70, 70, 70, 255), stop:0.142045 rgba(70, 70, 70, 255), stop:0.494318 rgba(12, 12, 12, 255), stop:1 rgba(12, 12, 12, 255));\n"
"border: 1px solid white;\n"
"border-radius: 5px;")
        self.label_pl_1_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pl_1_name.setObjectName("label_pl_1_name")
        self.verticalLayout.addWidget(self.label_pl_1_name)
        self.label_pl_1_btc = QtWidgets.QLabel(self.frame_pl_1_det)
        self.label_pl_1_btc.setMinimumSize(QtCore.QSize(110, 26))
        self.label_pl_1_btc.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_pl_1_btc.setStyleSheet("color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(70, 70, 70, 255), stop:0.142045 rgba(70, 70, 70, 255), stop:0.494318 rgba(12, 12, 12, 255), stop:1 rgba(12, 12, 12, 255));\n"
"border: 1px solid white;\n"
"border-radius: 5px;")
        self.label_pl_1_btc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pl_1_btc.setObjectName("label_pl_1_btc")
        self.verticalLayout.addWidget(self.label_pl_1_btc)
        self.label_p1c1 = QtWidgets.QLabel(self.frame_pl_1)
        self.label_p1c1.setGeometry(QtCore.QRect(40, 12, 35, 50))
        self.label_p1c1.setMinimumSize(QtCore.QSize(0, 50))
        self.label_p1c1.setMaximumSize(QtCore.QSize(35, 50))
        self.label_p1c1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_p1c1.setStyleSheet("")
        self.label_p1c1.setText("")
        self.label_p1c1.setPixmap(QtGui.QPixmap("./src/UI/images/41x60/back.png"))
        self.label_p1c1.setScaledContents(True)
        self.label_p1c1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_p1c1.setObjectName("label_p1c1")
        self.label_p1c2 = QtWidgets.QLabel(self.frame_pl_1)
        self.label_p1c2.setGeometry(QtCore.QRect(85, 12, 35, 50))
        self.label_p1c2.setMinimumSize(QtCore.QSize(0, 50))
        self.label_p1c2.setMaximumSize(QtCore.QSize(35, 50))
        self.label_p1c2.setStyleSheet("")
        self.label_p1c2.setText("")
        self.label_p1c2.setPixmap(QtGui.QPixmap("./src/UI/images/41x60/back.png"))
        self.label_p1c2.setScaledContents(True)
        self.label_p1c2.setObjectName("label_p1c2")
        self.frame_14 = QtWidgets.QFrame(self.frame_pl_1)
        self.frame_14.setGeometry(QtCore.QRect(30, 119, 115, 22))
        self.frame_14.setMinimumSize(QtCore.QSize(100, 22))
        self.frame_14.setMaximumSize(QtCore.QSize(115, 30))
        self.frame_14.setStyleSheet("#frame_14{\n"
"    border: none;\n"
"}")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_pl_1_dealer = QtWidgets.QLabel(self.frame_14)
        self.label_pl_1_dealer.setMinimumSize(QtCore.QSize(21, 21))
        self.label_pl_1_dealer.setMaximumSize(QtCore.QSize(21, 21))
        self.label_pl_1_dealer.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(0, 30, 13, 255), stop:0.272727 rgba(0, 64, 28, 255), stop:0.6875 rgba(0, 54, 23, 255), stop:1 rgba(0, 16, 7, 255));\n"
"color: white;\n"
"font: 10pt \"Montserrat\";\n"
"border: 2px solid black;\n"
"border-style: inset;\n"
"border-color: rgb(0, 34, 14);\n"
"padding-left: 2px;\n"
"border-radius: 5px;")
        self.label_pl_1_dealer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pl_1_dealer.setObjectName("label_pl_1_dealer")
        self.horizontalLayout_2.addWidget(self.label_pl_1_dealer)
        self.label_pl_1_bet = QtWidgets.QLabel(self.frame_14)
        self.label_pl_1_bet.setMinimumSize(QtCore.QSize(21, 21))
        self.label_pl_1_bet.setMaximumSize(QtCore.QSize(21, 21))
        self.label_pl_1_bet.setText("")
        self.label_pl_1_bet.setPixmap(QtGui.QPixmap("./src/UI/images/jLyAbQqTfW.png"))
        self.label_pl_1_bet.setScaledContents(True)
        self.label_pl_1_bet.setObjectName("label_pl_1_bet")
        self.horizontalLayout_2.addWidget(self.label_pl_1_bet)
        self.label_pl_1_bet_amt = QtWidgets.QLabel(self.frame_14)
        self.label_pl_1_bet_amt.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_pl_1_bet_amt.setStyleSheet("color: white;\n"
"font: 11pt \"Montserrat\";\n"
"border-radius: 5px;\n"
"background-color: transparent;")
        self.label_pl_1_bet_amt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_pl_1_bet_amt.setWordWrap(True)
        self.label_pl_1_bet_amt.setObjectName("label_pl_1_bet_amt")
        self.horizontalLayout_2.addWidget(self.label_pl_1_bet_amt)
        self.pl_1_avatar = QtWidgets.QLabel(self.frame_pl_1)
        self.pl_1_avatar.setGeometry(QtCore.QRect(50, 12, 50, 50))
        self.pl_1_avatar.setMinimumSize(QtCore.QSize(50, 50))
        self.pl_1_avatar.setText("")
        self.pl_1_avatar.setPixmap(QtGui.QPixmap("./src/UI/images/ksdfvQWC.png"))
        self.pl_1_avatar.setScaledContents(True)
        self.pl_1_avatar.setObjectName("pl_1_avatar")
        self.frame_16 = QtWidgets.QFrame(self.frame)
        self.frame_16.setGeometry(QtCore.QRect(540, 150, 100, 23))
        self.frame_16.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_16.setMaximumSize(QtCore.QSize(110, 30))
        self.frame_16.setStyleSheet("#frame_16{\n"
"    border: none;\n"
"}")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_pl_2_bet = QtWidgets.QLabel(self.frame_16)
        self.label_pl_2_bet.setMinimumSize(QtCore.QSize(21, 21))
        self.label_pl_2_bet.setMaximumSize(QtCore.QSize(21, 21))
        self.label_pl_2_bet.setText("")
        self.label_pl_2_bet.setPixmap(QtGui.QPixmap("./src/UI/images/jLyAbQqTfW.png"))
        self.label_pl_2_bet.setScaledContents(True)
        self.label_pl_2_bet.setObjectName("label_pl_2_bet")
        self.horizontalLayout_5.addWidget(self.label_pl_2_bet)
        self.label_pl_2_bet_amt = QtWidgets.QLabel(self.frame_16)
        self.label_pl_2_bet_amt.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_pl_2_bet_amt.setStyleSheet("color: white;\n"
"font: 11pt \"Montserrat\";\n"
"border-radius: 5px;\n"
"background-color: transparent;")
        self.label_pl_2_bet_amt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_pl_2_bet_amt.setWordWrap(True)
        self.label_pl_2_bet_amt.setObjectName("label_pl_2_bet_amt")
        self.horizontalLayout_5.addWidget(self.label_pl_2_bet_amt)
        self.label_pl_2_dealer = QtWidgets.QLabel(self.frame_16)
        self.label_pl_2_dealer.setMinimumSize(QtCore.QSize(21, 21))
        self.label_pl_2_dealer.setMaximumSize(QtCore.QSize(21, 21))
        self.label_pl_2_dealer.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(0, 30, 13, 255), stop:0.272727 rgba(0, 64, 28, 255), stop:0.6875 rgba(0, 54, 23, 255), stop:1 rgba(0, 16, 7, 255));\n"
"color: white;\n"
"font: 10pt \"Montserrat\";\n"
"border: 2px solid black;\n"
"border-style: inset;\n"
"border-color: rgb(0, 34, 14);\n"
"padding-left: 2px;\n"
"border-radius: 5px;")
        self.label_pl_2_dealer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pl_2_dealer.setObjectName("label_pl_2_dealer")
        self.horizontalLayout_5.addWidget(self.label_pl_2_dealer)
        self.frame_pl_2 = QtWidgets.QFrame(self.frame)
        self.frame_pl_2.setGeometry(QtCore.QRect(640, 40, 150, 140))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_pl_2.sizePolicy().hasHeightForWidth())
        self.frame_pl_2.setSizePolicy(sizePolicy)
        self.frame_pl_2.setMinimumSize(QtCore.QSize(150, 130))
        self.frame_pl_2.setMaximumSize(QtCore.QSize(108, 140))
        self.frame_pl_2.setStyleSheet("#frame_pl_2{\n"
"    border: none;\n"
"}")
        self.frame_pl_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pl_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pl_2.setObjectName("frame_pl_2")
        self.frame_10 = QtWidgets.QFrame(self.frame_pl_2)
        self.frame_10.setGeometry(QtCore.QRect(0, 70, 151, 60))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_10.setStyleSheet("#frame_10{\n"
"    border: none;\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_pl_2_name = QtWidgets.QLabel(self.frame_10)
        self.label_pl_2_name.setMinimumSize(QtCore.QSize(110, 26))
        self.label_pl_2_name.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_pl_2_name.setStyleSheet("color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(70, 70, 70, 255), stop:0.142045 rgba(70, 70, 70, 255), stop:0.494318 rgba(12, 12, 12, 255), stop:1 rgba(12, 12, 12, 255));\n"
"border: 1px solid white;\n"
"border-radius: 5px;")
        self.label_pl_2_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pl_2_name.setObjectName("label_pl_2_name")
        self.verticalLayout_2.addWidget(self.label_pl_2_name)
        self.label_pl_2_btc = QtWidgets.QLabel(self.frame_10)
        self.label_pl_2_btc.setMinimumSize(QtCore.QSize(110, 26))
        self.label_pl_2_btc.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_pl_2_btc.setStyleSheet("color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(70, 70, 70, 255), stop:0.142045 rgba(70, 70, 70, 255), stop:0.494318 rgba(12, 12, 12, 255), stop:1 rgba(12, 12, 12, 255));\n"
"border: 1px solid white;\n"
"border-radius: 5px;")
        self.label_pl_2_btc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pl_2_btc.setObjectName("label_pl_2_btc")
        self.verticalLayout_2.addWidget(self.label_pl_2_btc)
        self.label_p2c1 = QtWidgets.QLabel(self.frame_pl_2)
        self.label_p2c1.setGeometry(QtCore.QRect(40, 21, 35, 50))
        self.label_p2c1.setMinimumSize(QtCore.QSize(0, 50))
        self.label_p2c1.setMaximumSize(QtCore.QSize(35, 50))
        self.label_p2c1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_p2c1.setStyleSheet("")
        self.label_p2c1.setText("")
        self.label_p2c1.setPixmap(QtGui.QPixmap("./src/UI/images/41x60/back.png"))
        self.label_p2c1.setScaledContents(True)
        self.label_p2c1.setObjectName("label_p2c1")
        self.label_p2c2 = QtWidgets.QLabel(self.frame_pl_2)
        self.label_p2c2.setGeometry(QtCore.QRect(85, 21, 35, 50))
        self.label_p2c2.setMinimumSize(QtCore.QSize(0, 50))
        self.label_p2c2.setMaximumSize(QtCore.QSize(35, 50))
        self.label_p2c2.setStyleSheet("")
        self.label_p2c2.setText("")
        self.label_p2c2.setPixmap(QtGui.QPixmap("./src/UI/images/41x60/back.png"))
        self.label_p2c2.setScaledContents(True)
        self.label_p2c2.setObjectName("label_p2c2")
        self.pl_2_avatar = QtWidgets.QLabel(self.frame_pl_2)
        self.pl_2_avatar.setGeometry(QtCore.QRect(50, 21, 50, 50))
        self.pl_2_avatar.setMinimumSize(QtCore.QSize(50, 50))
        self.pl_2_avatar.setText("")
        self.pl_2_avatar.setPixmap(QtGui.QPixmap("./src/UI/images/ksdfvQWC.png"))
        self.pl_2_avatar.setScaledContents(True)
        self.pl_2_avatar.setObjectName("pl_2_avatar")
        self.layoutWidget3 = QtWidgets.QWidget(self.frame_pl_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 0, 130, 23))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_7.setContentsMargins(9, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.clock_label_2 = QtWidgets.QLabel(self.layoutWidget3)
        self.clock_label_2.setMinimumSize(QtCore.QSize(20, 21))
        self.clock_label_2.setMaximumSize(QtCore.QSize(20, 21))
        self.clock_label_2.setText("")
        self.clock_label_2.setPixmap(QtGui.QPixmap("./src/UI/images/fo2woqfz1mxw.png"))
        self.clock_label_2.setScaledContents(True)
        self.clock_label_2.setObjectName("clock_label_2")
        self.horizontalLayout_7.addWidget(self.clock_label_2)
        self.progressBar_pl_2 = QtWidgets.QProgressBar(self.layoutWidget3)
        self.progressBar_pl_2.setMinimumSize(QtCore.QSize(100, 15))
        self.progressBar_pl_2.setMaximumSize(QtCore.QSize(100, 15))
        self.progressBar_pl_2.setStyleSheet("border-left: none;\n"
"margin-left: -2px;")
        self.progressBar_pl_2.setProperty("value", 25)
        self.progressBar_pl_2.setTextVisible(False)
        self.progressBar_pl_2.setObjectName("progressBar_pl_2")
        self.horizontalLayout_7.addWidget(self.progressBar_pl_2)
        self.layoutWidget4 = QtWidgets.QWidget(self.frame)
        self.layoutWidget4.setGeometry(QtCore.QRect(220, 30, 130, 23))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_3.setContentsMargins(9, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.clock_label_1 = QtWidgets.QLabel(self.layoutWidget4)
        self.clock_label_1.setMinimumSize(QtCore.QSize(20, 21))
        self.clock_label_1.setMaximumSize(QtCore.QSize(20, 21))
        self.clock_label_1.setText("")
        self.clock_label_1.setPixmap(QtGui.QPixmap("./src/UI/images/fo2woqfz1mxw.png"))
        self.clock_label_1.setScaledContents(True)
        self.clock_label_1.setObjectName("clock_label_1")
        self.horizontalLayout_3.addWidget(self.clock_label_1)
        self.progressBar_pl_1 = QtWidgets.QProgressBar(self.layoutWidget4)
        self.progressBar_pl_1.setEnabled(True)
        self.progressBar_pl_1.setMinimumSize(QtCore.QSize(100, 15))
        self.progressBar_pl_1.setMaximumSize(QtCore.QSize(100, 15))
        self.progressBar_pl_1.setStyleSheet("border-left: none;\n"
"margin-left: -2px;")
        self.progressBar_pl_1.setProperty("value", 25)
        self.progressBar_pl_1.setTextVisible(False)
        self.progressBar_pl_1.setObjectName("progressBar_pl_1")
        self.horizontalLayout_3.addWidget(self.progressBar_pl_1)
        self.progressBar_pl_1.raise_()
        self.clock_label_1.raise_()
        self.layoutWidget5 = QtWidgets.QWidget(self.frame)
        self.layoutWidget5.setGeometry(QtCore.QRect(230, 410, 130, 23))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_11.setContentsMargins(9, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.clock_label_4 = QtWidgets.QLabel(self.layoutWidget5)
        self.clock_label_4.setMinimumSize(QtCore.QSize(20, 21))
        self.clock_label_4.setMaximumSize(QtCore.QSize(20, 21))
        self.clock_label_4.setText("")
        self.clock_label_4.setPixmap(QtGui.QPixmap("./src/UI/images/fo2woqfz1mxw.png"))
        self.clock_label_4.setScaledContents(True)
        self.clock_label_4.setObjectName("clock_label_4")
        self.horizontalLayout_11.addWidget(self.clock_label_4)
        self.progressBar_pl_4 = QtWidgets.QProgressBar(self.layoutWidget5)
        self.progressBar_pl_4.setMinimumSize(QtCore.QSize(100, 15))
        self.progressBar_pl_4.setMaximumSize(QtCore.QSize(100, 15))
        self.progressBar_pl_4.setStyleSheet("border-left: none;\n"
"margin-left: -2px;")
        self.progressBar_pl_4.setProperty("value", 25)
        self.progressBar_pl_4.setTextVisible(False)
        self.progressBar_pl_4.setObjectName("progressBar_pl_4")
        self.horizontalLayout_11.addWidget(self.progressBar_pl_4)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.frame_pl_1.raise_()
        self.frame_pl_4.raise_()
        self.frame_17.raise_()
        self.frame_pl_6.raise_()
        self.frame_pl_3.raise_()
        self.frame_pl_5.raise_()
        self.frame_19.raise_()
        self.frame_15.raise_()
        self.frame_table_top.raise_()
        self.frame_16.raise_()
        self.frame_pl_2.raise_()
        self.gridLayout.addWidget(self.frame, 2, 0, 3, 1)
        self.frame_12 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setMinimumSize(QtCore.QSize(350, 0))
        self.frame_12.setStyleSheet("#frame_12{\n"
"    border: none;\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_11.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.spinBox = QtWidgets.QSpinBox(self.frame_12)
        self.spinBox.setAutoFillBackground(True)
        self.spinBox.setStyleSheet("QSpinBox::up-button,QSpinBox::down-button{\n"
"background-color: none;    \n"
"}")
        self.spinBox.setFrame(False)
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox.setMaximum(9999999)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_11.addWidget(self.spinBox, 0, 3, 1, 1)
        self.pushButton_fold = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_fold.setStyleSheet("color: white;\n"
"font: 75 11pt \"Nirmala UI\";\n"
"background-color: maroon;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./src/UI/images/ruJIWvJn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_fold.setIcon(icon2)
        self.pushButton_fold.setObjectName("pushButton_fold")
        self.gridLayout_11.addWidget(self.pushButton_fold, 0, 6, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem4, 0, 5, 1, 1)
        self.pushButton_raise = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_raise.setStyleSheet("color: white;\n"
"font: 75 11pt \"Nirmala UI\";\n"
"background-color: maroon;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./src/UI/images/mMFIwrtF.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_raise.setIcon(icon3)
        self.pushButton_raise.setObjectName("pushButton_raise")
        self.gridLayout_11.addWidget(self.pushButton_raise, 0, 4, 1, 1)
        self.horizontalSlider_amt = QtWidgets.QSlider(self.frame_12)
        self.horizontalSlider_amt.setStyleSheet("QSlider:disabled {\n"
"  background: #19232D;\n"
"}\n"
"\n"
"QSlider:focus {\n"
"  border: none;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"  background: #32414B;\n"
"  border: 1px solid #32414B;\n"
"  height: 4px;\n"
"  margin: 0px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"  background: #32414B;\n"
"  border: 1px solid #32414B;\n"
"  width: 4px;\n"
"  margin: 0px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"  background: #1464A0;\n"
"  border: 1px solid #32414B;\n"
"  width: 4px;\n"
"  margin: 0px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical :disabled {\n"
"  background: #14506E;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"  background: #1464A0;\n"
"  border: 1px solid #32414B;\n"
"  height: 4px;\n"
"  margin: 0px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"  background: #14506E;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"  background: #787878;\n"
"  border: 1px solid #32414B;\n"
"  width: 8px;\n"
"  height: 8px;\n"
"  margin: -8px 0px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"  background: #148CD2;\n"
"  border: 1px solid #148CD2;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:focus {\n"
"  border: 1px solid #1464A0;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"  background: #787878;\n"
"  border: 1px solid #32414B;\n"
"  width: 8px;\n"
"  height: 8px;\n"
"  margin: 0 -8px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:vertical:hover {\n"
"  background: #148CD2;\n"
"  border: 1px solid #148CD2;\n"
"}\n"
"\n"
"QSlider::handle:vertical:focus {\n"
"  border: 1px solid #1464A0;\n"
"}")
        self.horizontalSlider_amt.setMaximum(9999999)
        self.horizontalSlider_amt.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_amt.setObjectName("horizontalSlider_amt")
        self.gridLayout_11.addWidget(self.horizontalSlider_amt, 0, 2, 1, 1)
        self.pushButton_call = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_call.setStyleSheet("color: white;\n"
"font: 75 11pt \"Nirmala UI\";\n"
"background-color: maroon;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./src/UI/images/zPQCbzZKE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_call.setIcon(icon4)
        self.pushButton_call.setObjectName("pushButton_call")
        self.gridLayout_11.addWidget(self.pushButton_call, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem5, 0, 7, 1, 1)
        self.gridLayout.addWidget(self.frame_12, 8, 0, 1, 2)
        self.frame_13 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_13.setStyleSheet("#frame_13{\n"
"    border: none;\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_10.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_10.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lineEdit_chat = QtWidgets.QLineEdit(self.frame_13)
        self.lineEdit_chat.setMinimumSize(QtCore.QSize(260, 25))
        self.lineEdit_chat.setMaximumSize(QtCore.QSize(250, 30))
        self.lineEdit_chat.setStyleSheet("#lineEdit_chat{\n"
"color: white;\n"
"background-color:rgb(70, 70, 70);\n"
"border-radius: 2px;\n"
"padding: 2px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"border-left-color: black;\n"
"}")
        self.lineEdit_chat.setObjectName("lineEdit_chat")
        self.gridLayout_10.addWidget(self.lineEdit_chat, 1, 0, 1, 1)
        self.chat_area = QtWidgets.QScrollArea(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chat_area.sizePolicy().hasHeightForWidth())
        self.chat_area.setSizePolicy(sizePolicy)
        self.chat_area.setMinimumSize(QtCore.QSize(260, 400))
        self.chat_area.setBaseSize(QtCore.QSize(0, 0))
        self.chat_area.setStyleSheet("#chat_area{\n"
"background-color: transparent;\n"
"border: 2px solid grey;\n"
"border-radius: 10px;\n"
"}")
        self.chat_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.chat_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.chat_area.setWidgetResizable(True)
        self.chat_area.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.chat_area.setObjectName("chat_area")
        self.chat_scroll_area = QtWidgets.QWidget()
        self.chat_scroll_area.setGeometry(QtCore.QRect(0, 0, 256, 396))
        self.chat_scroll_area.setStyleSheet("#chat_scroll_area{\n"
"background-color: rgba(148, 148, 148, 120);\n"
"border: 2px solid rgb(70, 70, 70);\n"
"border-radius: 10px;\n"
"padding: 10px 2px 2px 10px;\n"
"}")
        self.chat_scroll_area.setObjectName("chat_scroll_area")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.chat_scroll_area)
        self.verticalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.chat_area.setWidget(self.chat_scroll_area)
        self.gridLayout_10.addWidget(self.chat_area, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_13, 2, 2, 7, 1)
        self.frame_board = QtWidgets.QFrame(self.centralwidget)
        self.frame_board.setGeometry(QtCore.QRect(9, 99, 785, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_board.sizePolicy().hasHeightForWidth())
        self.frame_board.setSizePolicy(sizePolicy)
        self.frame_board.setMinimumSize(QtCore.QSize(785, 500))
        self.frame_board.setStyleSheet("#frame_board{\n"
"border-image: url(./src/UI/images/FJKdWJ.png);\n"
"border: none;\n"
"}")
        self.frame_board.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_board.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_board.setObjectName("frame_board")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_board)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_12.raise_()
        self.frame_13.raise_()
        self.frame_header.raise_()
        self.frame_board.raise_()
        self.frame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.horizontalSlider_amt.valueChanged['int'].connect(self.spinBox.setValue)
        self.spinBox.valueChanged['int'].connect(self.horizontalSlider_amt.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Torpoker"))
        self.label_pl_5_dealer.setText(_translate("MainWindow", "D"))
        self.label_pl_5_bet_amt.setText(_translate("MainWindow", "1000"))
        self.label_pl_6_name.setText(_translate("MainWindow", "player 6"))
        self.label_pl_6_btc.setText(_translate("MainWindow", "TextLabel"))
        self.label_pl_3_name.setText(_translate("MainWindow", "player 3"))
        self.label_pl_3_btc.setText(_translate("MainWindow", "TextLabel"))
        self.label_pl_4_name.setText(_translate("MainWindow", "player 4"))
        self.label_pl_4_btc.setText(_translate("MainWindow", "TextLabel"))
        self.label_pl_4_dealer.setText(_translate("MainWindow", "D"))
        self.label_pl_4_bet_amt.setText(_translate("MainWindow", "1000"))
        self.label_pl_5_name.setText(_translate("MainWindow", "player 5"))
        self.label_pl_5_btc.setText(_translate("MainWindow", "TextLabel"))
        self.label_pl_3_bet_amt.setText(_translate("MainWindow", "1000"))
        self.label_pl_3_dealer.setText(_translate("MainWindow", "D"))
        self.label_pl_6_dealer.setText(_translate("MainWindow", "D"))
        self.label_pl_6_bet_amt.setText(_translate("MainWindow", "1000"))
        self.label_result.setText(_translate("MainWindow", "result"))
        self.label_pot.setText(_translate("MainWindow", "Pot"))
        self.label_pl_1_name.setText(_translate("MainWindow", "player 1"))
        self.label_pl_1_btc.setText(_translate("MainWindow", "TextLabel"))
        self.label_pl_1_dealer.setText(_translate("MainWindow", "D"))
        self.label_pl_1_bet_amt.setText(_translate("MainWindow", "1000"))
        self.label_pl_2_bet_amt.setText(_translate("MainWindow", "1000"))
        self.label_pl_2_dealer.setText(_translate("MainWindow", "D"))
        self.label_pl_2_name.setText(_translate("MainWindow", "player 2"))
        self.label_pl_2_btc.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_fold.setText(_translate("MainWindow", "FOLD"))
        self.pushButton_raise.setText(_translate("MainWindow", "RAISE"))
        self.pushButton_call.setText(_translate("MainWindow", "CALL"))
        self.lineEdit_chat.setPlaceholderText(_translate("MainWindow", "Enter Message Here"))
