# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\btc_deposit_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(524, 366)
        Dialog.setStyleSheet("#Dialog{\n"
"background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0113636, x2:0.506, y2:1, stop:0 rgba(72, 72, 72, 255), stop:1 rgba(30, 30, 30, 255));\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_header = QtWidgets.QLabel(Dialog)
        self.label_header.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_header.setFont(font)
        self.label_header.setStyleSheet("color: white;")
        self.label_header.setWordWrap(True)
        self.label_header.setObjectName("label_header")
        self.gridLayout.addWidget(self.label_header, 3, 0, 1, 2)
        self.lineEdit_deposit_address = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(9)
        self.lineEdit_deposit_address.setFont(font)
        self.lineEdit_deposit_address.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_deposit_address.setInputMask("")
        self.lineEdit_deposit_address.setText("")
        self.lineEdit_deposit_address.setMaxLength(32767)
        self.lineEdit_deposit_address.setObjectName("lineEdit_deposit_address")
        self.gridLayout.addWidget(self.lineEdit_deposit_address, 4, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 2)
        self.label_footer = QtWidgets.QLabel(Dialog)
        self.label_footer.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_footer.setFont(font)
        self.label_footer.setStyleSheet("color: white;")
        self.label_footer.setWordWrap(True)
        self.label_footer.setObjectName("label_footer")
        self.gridLayout.addWidget(self.label_footer, 6, 0, 1, 2)
        self.label_descr = QtWidgets.QLabel(Dialog)
        self.label_descr.setMinimumSize(QtCore.QSize(0, 50))
        self.label_descr.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(13)
        self.label_descr.setFont(font)
        self.label_descr.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0.83, y1:0.637045, x2:1, y2:0.727, stop:0 rgba(128, 128, 128, 255), stop:0.482955 rgba(122, 122, 122, 255), stop:0.738636 rgba(90, 90, 90, 237), stop:0.948864 rgba(129, 129, 129, 232), stop:0.954545 rgba(135, 135, 135, 255));\n"
"padding-left: 50px;\n"
"color: white;")
        self.label_descr.setObjectName("label_descr")
        self.gridLayout.addWidget(self.label_descr, 0, 0, 1, 2)
        self.label_status = QtWidgets.QLabel(Dialog)
        self.label_status.setStyleSheet("color: white;")
        self.label_status.setObjectName("label_status")
        self.gridLayout.addWidget(self.label_status, 8, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem2, 7, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Torpoker"))
        self.label_header.setText(_translate("Dialog", "Minimum deposit MINDEPOSIT.\n"
"Personal address:"))
        self.label_footer.setText(_translate("Dialog", "Please wait for the confirmation of the transaction. Address valid for a single transaction. Do not close this window."))
        self.label_descr.setText(_translate("Dialog", "STEP 2/2 - Send BTC"))
        self.label_status.setText(_translate("Dialog", "waiting..."))
