# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(540, 322)
        Dialog.setStyleSheet("#Dialog{\n"
"background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0113636, x2:0.506, y2:1, stop:0 rgba(72, 72, 72, 255), stop:1 rgba(30, 30, 30, 255));\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setMinimumSize(QtCore.QSize(0, 50))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0.83, y1:0.637045, x2:1, y2:0.727, stop:0 rgba(128, 128, 128, 255), stop:0.482955 rgba(122, 122, 122, 255), stop:0.738636 rgba(90, 90, 90, 237), stop:0.948864 rgba(129, 129, 129, 232), stop:0.954545 rgba(135, 135, 135, 255));\n"
"padding-left: 50px;\n"
"color: white;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_btc_amt = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(9)
        self.lineEdit_btc_amt.setFont(font)
        self.lineEdit_btc_amt.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_btc_amt.setInputMask("")
        self.lineEdit_btc_amt.setText("")
        self.lineEdit_btc_amt.setMaxLength(32767)
        self.lineEdit_btc_amt.setObjectName("lineEdit_btc_amt")
        self.verticalLayout.addWidget(self.lineEdit_btc_amt)
        self.pushButton_submit = QtWidgets.QPushButton(Dialog)
        self.pushButton_submit.setStyleSheet("color: white;\n"
"background-color: maroon;\n"
"font: 10pt \"Montserrat\";")
        self.pushButton_submit.setObjectName("pushButton_submit")
        self.verticalLayout.addWidget(self.pushButton_submit)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Torpoker"))
        self.label_2.setText(_translate("Dialog", "JOIN"))
        self.label.setText(_translate("Dialog", "The amount has to be between min and max to join the table."))
        self.pushButton_submit.setText(_translate("Dialog", "Submit"))
